version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hackathon
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=admin007
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db