# Generated by Django 3.0.5 on 2020-11-13 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('seller_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
                ('date', models.DateTimeField()),
                ('order_type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('user_xp', models.PositiveIntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numbers are Allowed')])),
                ('reg_no', models.CharField(max_length=15)),
                ('id_card', models.FileField(upload_to='')),
                ('bank_ac', models.CharField(max_length=20)),
                ('rating', models.PositiveIntegerField()),
                ('total_ratings', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('main_cat', models.CharField(max_length=30)),
                ('sub_cat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('seller', models.UUIDField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('total_ratings', models.PositiveIntegerField(default=100)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('base_price', models.PositiveIntegerField()),
                ('discount', models.FloatField(default=0)),
                ('description', models.TextField(default='Some Product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sub_Category')),
            ],
        ),
    ]
