# Generated by Django 3.0.5 on 2020-11-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bs_category',
            field=models.CharField(choices=[('-', '-'), ('Electronics', 'Electronics'), ('Stationary', 'Stationary'), ('Art and Craft', 'Art and Craft'), ('Grocery', 'Grocery')], max_length=30),
        ),
    ]
