# Generated by Django 3.0.5 on 2020-11-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.AlterField(
            model_name='seller',
            name='bs_category',
            field=models.CharField(choices=[('Literature and Stationary', 'Literature and Stationary')], max_length=30),
        ),
    ]
