# Generated by Django 3.0.5 on 2020-11-16 07:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='img',
            field=models.ImageField(default='/static/assets/images/products.svg', upload_to=core.models.img_path),
        ),
    ]
