# Generated by Django 3.0.5 on 2020-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
