# Generated by Django 3.0.5 on 2020-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Reviewing', 'Reviewing')], default='Reviewing', max_length=20),
        ),
    ]
