# Generated by Django 3.0.5 on 2020-11-17 04:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201116_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product_list',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='img',
            field=models.ImageField(default='/product.svg', upload_to=core.models.img_path),
        ),
    ]
