# Generated by Django 3.0.5 on 2020-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201120_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='nos',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
