# Generated by Django 3.0.5 on 2020-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201114_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
