# Generated by Django 3.0.5 on 2020-11-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cart_nos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='img',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='pan_card',
        ),
    ]
