# Generated by Django 3.1.3 on 2020-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201122_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
