# Generated by Django 3.0.5 on 2020-11-15 11:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201114_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(upload_to=core.models.sheet_path)),
            ],
        ),
    ]
