# Generated by Django 3.0.5 on 2020-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sheetmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='img',
        ),
        migrations.AlterField(
            model_name='product_list',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product_list',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
