# Generated by Django 3.0.5 on 2020-11-22 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[+]{0,1}[0-9]{10,12}', 'Only Numbers are Allowed')]),
        ),
    ]
